ENGLISH_EXAMPLES = {
    ".helphide имя_модуля": ".helphide module_name",
    ".suspend секунды": ".suspend seconds",
    ".addacc имя": ".addacc name",
    ".suspend_api_protect секунды": ".suspend_api_protect seconds",
    ".newsgroup имя": ".newsgroup name",
    ".delsgroup имя CONFIRM": ".delsgroup name CONFIRM",
    ".tsec user|chat|group ID команда 1h": ".tsec user|chat|group ID command 1h",
    ".addalias имя команда": ".addalias name command",
    ".clearmodule имя CONFIRM": ".clearmodule name CONFIRM",
    ".terminal команда": ".terminal command",
    ".dllangpack https://адрес/пакет.json": ".dllangpack https://host/pack.json",
    ".tr язык текст": ".tr language text",
    "нет": "none",
}


ENGLISH_PHRASES = {
    "Модуль справки нельзя скрыть.": "The Help module cannot be hidden.",
    "Модуль не найден.": "Module not found.",
    "Potato перезапускается.": "Potato is restarting.",
    "Ответьте": "Reply",
    " на сообщение с ": " to a message containing a ",
    "-файлом.": " file.",
    " снова отображается": " is visible again",
    " скрыт из справки": " is hidden from Help",
    "Модуль ": "Module ",
    "Файл ": "File ",
    "Ошибки модулей": "Module errors",
    "Вебхуки": "Webhooks",
    "подпись провайдера": "provider signature",
    "Удаление:": "Remove:",
    "номер": "number",
    "уже авторизован.": "is already authorized.",
    "Аккаунт ": "Account ",
    "Вход в Potato:": "Potato login:",
    "Сканируйте в Telegram → Настройки → Устройства. QR-код никому не пересылайте.": "Scan in Telegram → Settings → Devices. Do not share the QR code.",
    "Завершите вход в CLI:": "Complete login in the CLI:",
    "Повторите .addacc.": "Try .addacc again.",
    "Повторите вход.": "Log in again.",
    "Добавьте аккаунт через .addacc или CLI.": "Add an account with .addacc or the CLI.",
    "группы,": "groups,",
    "личные,": "private chats,",
    "исходящие,": "outgoing,",
    "входящие.": "incoming.",
    "входящие": "incoming",
    " все.": " all.",
    " сохранены.": " saved.",
    "сохранены.": "saved.",
    "команда": "command",
    "секунды": "seconds",
    "от 0 до 300.": "from 0 to 300.",
    "Установка Potato": "Install Potato",
    "Алиасы": "Aliases",
    "Очистка данных модуля:": "Clear module data:",
    "Данные модуля ": "Module data for ",
    " очищены.": " cleared.",
    "Параметр ": "Setting ",
    " модуля ": " of module ",
    "Среда ": "Runtime ",
    " · ошибка сборки": " · build error",
    " · код ": " · exit code ",
    "добавлен в": "added to",
    "удалён из": "removed from",
    "Пользователь ": "User ",
    " группы ": " group ",
    "Проверьте команду и срок от 1s до 30d.": "Check the command and duration from 1s to 30d.",
    "Удалить все временные правила:": "Remove all temporary rules:",
    "Изменение:": "Change:",
    "Укажите числовой ID.": "Enter a numeric ID.",
    " на ": " for ",
    "Процесс ": "Process ",
    " останавливается.": " is stopping.",
    "Язык интерфейса:": "Interface language:",
    "Язык интерфейса изменён:": "Interface language changed:",
    "Доступны:": "Available:",
    "Язык не установлен.": "Language is not installed.",
    "для своего пакета.": "for a custom pack.",
    "Языковой пакет установлен:": "Language pack installed:",
    "Не удалось загрузить языковой пакет:": "Could not load language pack:",
    "язык текст": "language text",
    "Скрыть модуль из справки": "Hide a module from Help",
    "Адрес поддержки не настроен владельцем.": "The owner has not configured a support address.",
    "Ссылка на исходный код не настроена владельцем.": "The owner has not configured a source URL.",
    "Секреты вебхуков доступны только в Избранном.": "Webhook secrets are available only in Saved Messages.",
    "Отправьте .webhooks в личный чат с собой.": "Send .webhooks in Saved Messages.",
    "Загрузка модуля": "Load a module",
    "Модуль слишком большой.": "The module is too large.",
    "Не удалось скачать файл модуля.": "Could not download the module file.",
    "Не удалось подготовить модуль": "Could not stage the module",
    "Не удалось скачать модуль": "Could not download the module",
    "Не удалось загрузить каталог": "Could not load the catalog",
    "Не удалось установить зависимости": "Could not install dependencies",
    "Модуль не найден в добавленных репозиториях": "Module not found in added repositories",
    "Модуль не установлен и не ожидает установки": "Module is neither installed nor staged",
    "Каталог должен содержать от 1 до 30 модулей": "The catalog must contain 1 to 30 modules",
    "Сначала добавьте репозиторий командой .addrepo.": "Add a repository with .addrepo first.",
    "Укажите номер репозитория из .delrepo.": "Enter a repository number from .delrepo.",
    "Укажите имя модуля или прямую ссылку на .py": "Enter a module name or a direct .py URL",
    "Для применения выполните": "To apply, run",
    "Примените через .restart.": "Apply with .restart.",
    "Для установки ответьте на него .lm.": "Reply to it with .lm to install.",
    "Модуль отклонён": "Module rejected",
    "Репозиторий не добавлен": "Repository not added",
    "Репозиторий добавлен:": "Repository added:",
    "Репозиторий удалён:": "Repository removed:",
    "Репозитории модулей": "Module repositories",
    "Репозитории": "Repositories",
    "Модуль не удалён": "Module not removed",
    "Удалить все пользовательские модули:": "Remove all user modules:",
    "К удалению подготовлено модулей:": "Modules staged for removal:",
    "Подготовлено модулей:": "Modules staged:",
    "Зависимости:": "Dependencies:",
    "Максимум — 1 МиБ.": "Maximum: 1 MiB.",
    "Вебхуков пока нет.": "No webhooks yet.",
    "Журнал ошибок доступен только в Избранном.": "The error log is available only in Saved Messages.",
    "Ошибок модулей нет": "No module errors",
    "Очищено записей журнала:": "Log entries cleared:",
    "Поддержка Potato": "Potato support",
    "Исходный код Potato": "Potato source code",
    "Potato работает": "Potato is running",
    "Загруженные модули": "Loaded modules",
    "Полный список команд — .help": "Full command list: .help",
    "Модулей:": "Modules:",
    "Аккаунт:": "Account:",
    "Время работы:": "Uptime:",
    "Пинг Telegram:": "Telegram ping:",
    "Обработка сообщений ": "Message handling ",
    "Защита от частых API-вызовов ": "API flood protection ",
    "Не более 30 вызовов за 10 секунд через клиент Potato.": "At most 30 calls per 10 seconds through the Potato client.",
    "Защита API ": "API protection ",
    "Настройки модулей доступны только в Избранном.": "Module settings are available only in Saved Messages.",
    "Нет модулей с настраиваемыми параметрами": "No modules with configurable values",
    "Настраиваемые модули": "Configurable modules",
    "Схема настроек модуля некорректна.": "The module settings schema is invalid.",
    "У модуля нет настраиваемых параметров": "This module has no configurable values",
    "Значение должно быть корректным JSON.": "The value must be valid JSON.",
    "Параметр не найден.": "Setting not found.",
    "Ожидается тип ": "Expected type ",
    "Добавление аккаунта доступно только в Избранном.": "Adding an account is available only in Saved Messages.",
    "Переключение доступно только в Избранном.": "Switching accounts is available only in Saved Messages.",
    "Укажите новое имя аккаунта:": "Enter a new account name:",
    "Для аккаунта ": "Account ",
    " нужен пароль 2FA.": " requires a 2FA password.",
    "Время QR-входа истекло.": "QR login expired.",
    "Сохранённых сессий нет": "No saved sessions",
    "Сессия не найдена.": "Session not found.",
    "Сессия не авторизована.": "Session is not authorized.",
    "Этот аккаунт уже активен.": "This account is already active.",
    "Аккаунты Potato": "Potato accounts",
    "Переключение:": "Switch with:",
    "Переключаю Potato на аккаунт ": "Switching Potato to account ",
    "Настройки Potato": "Potato settings",
    "NoNick для всех групп:": "NoNick for all groups:",
    "NoNick для всех групп ": "NoNick for all groups ",
    "NoNick для ": "NoNick for ",
    "Обработчики сообщений": "Message watchers",
    "Нет обработчиков": "No watchers",
    "Настройки обработчика ": "Watcher settings for ",
    "Обработчик ": "Watcher ",
    "Укажите модуль из .watchers.": "Choose a module from .watchers.",
    "Команда доступна в группе.": "This command is available in a group.",
    "Укажите ID, @имя или ответьте на сообщение пользователя.": "Enter an ID or @username, or reply to a user's message.",
    "Фильтры:": "Filters:",
    "все сообщения": "all messages",
    "чатов в блокировке:": "blocked chats:",
    "пользователи": "users",
    "пользователя ": "user ",
    "этого чата": "this chat",
    "чаты": "chats",
    "команды ": "command ",
    "команды": "commands",
    "список пуст": "list is empty",
    "Пользовательских алиасов нет.": "No custom aliases.",
    "Алиас сохранён:": "Alias saved:",
    "Алиас удалён:": "Alias removed:",
    "Алиас не найден.": "Alias not found.",
    "Проверьте имя алиаса и существование команды.": "Check the alias name and target command.",
    "Префикс должен содержать от 1 до 3 непробельных символов.": "Prefix must contain 1 to 3 non-space characters.",
    "Дополнительный префикс:": "Additional prefix:",
    "Точка всегда остаётся доступна.": "The dot prefix remains available.",
    "Избранное нельзя заблокировать.": "Saved Messages cannot be blocked.",
    "Чат добавлен в чёрный список:": "Chat blocked:",
    "Чат исключён из чёрного списка:": "Chat unblocked:",
    "Пользователь заблокирован:": "User blocked:",
    "Пользователь разблокирован:": "User unblocked:",
    "Укажите другого пользователя ID, @имя или ответом на сообщение.": "Enter another user's ID or @username, or reply to a message.",
    "Укажите пользователя ID, @имя или ответом.": "Enter a user's ID or @username, or reply.",
    "Эту системную команду нельзя отключить.": "This system command cannot be disabled.",
    "Системные модули нельзя отключить.": "System modules cannot be disabled.",
    "Очищать можно только данные пользовательского модуля.": "Only user module data can be cleared.",
    "Для очистки базы отправьте": "To clear the database, send",
    "Настройки и данные модулей очищены.": "Settings and module data cleared.",
    "Сессия Telegram и файлы модулей сохранены.": "Telegram session and module files were kept.",
    "Открытый Telegram-юзербот для автоматизации процессов.": "Open Telegram userbot for automation.",
    "Инструкция: README.md в репозитории проекта.": "Instructions: README.md in the project repository.",
    "Добавление владельца:": "Add an owner:",
    "Удаление владельца:": "Remove an owner:",
    "Укажите ID другого пользователя.": "Enter another user's ID.",
    "Владелец добавлен:": "Owner added:",
    "Доверяйте только своему аккаунту: он сможет выполнять команды Potato.": "Trust only your own account: it can run Potato commands.",
    "Доступ отозван:": "Access revoked:",
    "Владельцы": "Owners",
    "Групп доступа пока нет.": "No access groups yet.",
    "Группы доступа": "Access groups",
    "Группа не найдена.": "Group not found.",
    "Группа создана:": "Group created:",
    "Группа удалена:": "Group removed:",
    "Укажите новое имя группы:": "Enter a new group name:",
    "Удаление группы:": "Remove group:",
    "Укажите группу и ID пользователя или ответьте на сообщение.": "Enter a group and user ID, or reply to a message.",
    "Пользователь не указан.": "User not specified.",
    "По умолчанию команды доступны владельцу.": "By default, commands are available to the owner.",
    "Недопустимое правило для этой команды.": "Invalid rule for this command.",
    "Команда не найдена.": "Command not found.",
    "Команда ": "Command ",
    "Список: .sgroups": "List: .sgroups",
    "Переключение: .switchacc имя": "Switch with: .switchacc name",
    "group:имя|default": "group:name|default",
    "Доступ к ": "Access to ",
    "Доступ выдан:": "Access granted:",
    "Права команд": "Command permissions",
    "Временные правила": "Temporary rules",
    "Временное правило удалено.": "Temporary rule removed.",
    "Временные правила удалены.": "Temporary rules removed.",
    "Временный доступ:": "Temporary access:",
    "Нет активных правил": "No active rules",
    "Inline-команды пока недоступны без отдельного Telegram-бота.": "Inline commands require a separate Telegram bot and are unavailable now.",
    "Inline-запросы пока недоступны без отдельного Telegram-бота.": "Inline queries require a separate Telegram bot and are unavailable now.",
    "Терминал · код ": "Terminal · exit code ",
    "Команды терминала доступны только в Избранном.": "Terminal commands are available only in Saved Messages.",
    "Остановка команд доступна только в Избранном.": "Stopping commands is available only in Saved Messages.",
    "Активных команд терминала нет.": "No active terminal commands.",
    "Процесс не найден.": "Process not found.",
    "Калькулятор доступен только в Избранном.": "The calculator is available only in Saved Messages.",
    "Исполнение кода доступно только в Избранном.": "Code execution is available only in Saved Messages.",
    "Укажите код до 32 КиБ или ответьте на сообщение с кодом.": "Enter up to 32 KiB of code or reply to a code message.",
    " не установлена в контейнере.": " is not installed in the container.",
    "Ошибка вычисления:": "Calculation error:",
    "Результат:": "Result:",
    "Разрешены только математические выражения": "Only mathematical expressions are allowed",
    "Некорректное выражение": "Invalid expression",
    "Выражение слишком сложное": "Expression is too complex",
    "Слишком большая степень": "Exponent is too large",
    "Результат выходит за допустимые пределы": "Result exceeds limits",
    "Выражение должно содержать от 1 до 1024 символов": "Expression must contain 1 to 1024 characters",
    "Точность округления вне допустимых пределов": "Rounding precision exceeds limits",
    "Превышено время выполнения.": "Execution timed out.",
    "Вывод пуст": "No output",
    "Перевод не выполнен": "Translation failed",
    "Перевод · ": "Translation · ",
    " или ответьте на сообщение.": " or reply to a message.",
    "Используйте": "Use",
    "Использование:": "Usage:",
    "Укажите": "Enter",
    "Список пуст": "List is empty",
    "без команд": "no commands",
    "справка": "Help",
    "продолжение": "continued",
    "в Избранном": "in Saved Messages",
    "в этом чате": "in this chat",
    "нет участников": "no members",
    " участников": " members",
    "основной": "primary",
    "включена": "enabled",
    "выключена": "disabled",
    "включён": "enabled",
    "выключен": "disabled",
    "отключён": "disabled",
    "отключена": "disabled",
    "возобновлена": "resumed",
    "приостановлена на ": "paused for ",
    "снова активна": "active again",
    "сохранён": "saved",
    "авторизован": "authorized",
    "ожидает установки": "is awaiting installation",
    "будет удалён после .restart.": "will be removed after .restart.",
    "отправлен.": "sent.",
    " секунды": " seconds",
    " сек.": " sec.",
    " мс": " ms",
}
